import java.io.*;import java.util.*;
/** Centralised text-file persistence for StayNest. */
public class FileManager {
 private final String accommodationsFilePath,usersFilePath,bookingsFilePath,evaluationsFilePath;
 public FileManager(String a,String u,String b,String e){accommodationsFilePath=a;usersFilePath=u;bookingsFilePath=b;evaluationsFilePath=e;}
 private List<String> read(String path){List<String> lines=new ArrayList<>();File f=new File(path);if(!f.exists()){System.out.println("[Info] No file found: "+path);return lines;}try(BufferedReader r=new BufferedReader(new FileReader(f))){String s;while((s=r.readLine())!=null)if(!s.trim().isEmpty())lines.add(s);}catch(IOException e){System.out.println("[Error] Could not read "+path+": "+e.getMessage());}return lines;}
 private void write(String path,List<String> lines){File f=new File(path);if(f.getParentFile()!=null)f.getParentFile().mkdirs();try(BufferedWriter w=new BufferedWriter(new FileWriter(f))){for(String s:lines){w.write(s);w.newLine();}}catch(IOException e){System.out.println("[Error] Could not save "+path+": "+e.getMessage());}}
 public List<Accommodation> loadAccommodations(){List<Accommodation> r=new ArrayList<>();for(String line:read(accommodationsFilePath))try{String[] p=line.split("\\|");String t=p[0].toUpperCase();double price=Double.parseDouble(p[4]);int max=Integer.parseInt(p[5]);boolean av=Boolean.parseBoolean(p[6]);if(t.equals("APARTMENT"))r.add(new Apartment(p[1],p[2],p[3],price,max,av,Integer.parseInt(p[7])));else if(t.equals("HOUSE"))r.add(new House(p[1],p[2],p[3],price,max,av,Boolean.parseBoolean(p[7]),Integer.parseInt(p[8])));else if(t.equals("VILLA"))r.add(new Villa(p[1],p[2],p[3],price,max,av,Boolean.parseBoolean(p[7]),Boolean.parseBoolean(p[8])));}catch(Exception e){System.out.println("[Warning] Skipping accommodation record: "+line);}return r;}
 public List<User> loadUsers(){List<User> r=new ArrayList<>();for(String s:read(usersFilePath))try{r.add(User.fromFileString(s));}catch(Exception e){System.out.println("[Warning] Skipping user record: "+s);}return r;}
 public List<Booking> loadBookings(){List<Booking> r=new ArrayList<>();for(String s:read(bookingsFilePath))try{r.add(Booking.fromFileString(s));}catch(Exception e){System.out.println("[Warning] Skipping booking record: "+s);}return r;}
 public List<Evaluation> loadEvaluations(){List<Evaluation> r=new ArrayList<>();for(String s:read(evaluationsFilePath))try{r.add(Evaluation.fromFileString(s));}catch(Exception e){System.out.println("[Warning] Skipping evaluation record: "+s);}return r;}
 public void saveAccommodations(List<Accommodation> x){List<String> r=new ArrayList<>();for(Accommodation a:x)r.add(a.toFileString());write(accommodationsFilePath,r);} public void saveUsers(List<User>x){List<String>r=new ArrayList<>();for(User u:x)r.add(u.toFileString());write(usersFilePath,r);} public void saveBookings(List<Booking>x){List<String>r=new ArrayList<>();for(Booking b:x)r.add(b.toFileString());write(bookingsFilePath,r);} public void saveEvaluations(List<Evaluation>x){List<String>r=new ArrayList<>();for(Evaluation e:x)r.add(e.toFileString());write(evaluationsFilePath,r);}
}
