import java.time.LocalDate;import java.time.format.DateTimeFormatter;import java.util.*;
/** Text-based StayNest interface. Group members: add your actual names before submission. */
public class Main{
 private static final Scanner sc=new Scanner(System.in); private static final DateTimeFormatter F=DateTimeFormatter.ISO_LOCAL_DATE; private static final BookingSystem system=new BookingSystem(); private static final FileManager fm=new FileManager("data/accommodations.txt","data/users.txt","data/bookings.txt","data/evaluations.txt");
 public static void main(String[] args){System.out.println("====================================");System.out.println(" Welcome to StayNest");System.out.println(" Accommodation Booking System");System.out.println("====================================");system.loadFromFiles(fm);System.out.println("Loaded "+system.getAllUsers().size()+" users, "+system.getAllAccommodations().size()+" accommodations, "+system.getAllBookings().size()+" bookings and "+system.getAllEvaluations().size()+" evaluations.\n");boolean run=true;while(run){mainMenu();switch(choice(0,5)){case 1:userMenu();break;case 2:accommodationMenu();break;case 3:bookingMenu();break;case 4:evaluationMenu();break;case 5:system.saveToFiles(fm);System.out.println("Data saved.");break;case 0:system.saveToFiles(fm);System.out.println("Data saved. Goodbye!");run=false;}}sc.close();}
 static void mainMenu(){System.out.println("\n------------- STAYNEST MAIN MENU -------------");System.out.println("1. Manage Users");System.out.println("2. Manage Accommodations");System.out.println("3. Manage Bookings");System.out.println("4. Evaluations / Feedback / Rewards / Penalties");System.out.println("5. Save data");System.out.println("0. Save and Exit");}
 static void userMenu(){while(true){System.out.println("\n------------- USER MANAGEMENT -------------");System.out.println("1. View all users\n2. Add user\n3. Search user\n4. Update user\n5. Delete user\n0. Back");try{switch(choice(0,5)){case 1:system.getAllUsers().forEach(System.out::println);break;case 2:addUser();break;case 3:searchUser();break;case 4:updateUser();break;case 5:deleteUser();break;default:return;}}catch(InvalidInputException e){System.out.println("[Error] "+e.getMessage());}}}
 static void addUser(){String id=system.generateUserId();String n=text("Name: "),e=text("Email: "),p=text("Phone: ");system.addUser(new User(id,n,e,p));System.out.println("User added: "+id);}
 static void searchUser(){String q=text("Search by ID, name or email: ");List<User> r=system.searchUsers(q);if(r.isEmpty())System.out.println("No users found.");else r.forEach(System.out::println);}
 static void updateUser()throws InvalidInputException{User u=system.findUserById(text("User ID: "));String n=optional("New name: ");String e=optional("New email: ");String p=optional("New phone: ");if(!n.isEmpty())u.setName(n);if(!e.isEmpty())u.setEmail(e);if(!p.isEmpty())u.setPhone(p);System.out.println("Updated: "+u);}
 static void deleteUser()throws InvalidInputException{String id=text("User ID: ");system.deleteUser(id);System.out.println("User deleted.");}
 static void accommodationMenu(){while(true){System.out.println("\n------------- ACCOMMODATIONS -------------");System.out.println("1. View all\n2. Add\n3. Update\n4. Delete\n5. Search location\n6. Search max price\n0. Back");try{switch(choice(0,6)){case 1:system.getAllAccommodations().forEach(System.out::println);break;case 2:addAccommodation();break;case 3:updateAccommodation();break;case 4:system.deleteAccommodation(text("Accommodation ID: "));break;case 5:system.searchByLocation(text("Location: ")).forEach(System.out::println);break;case 6:system.searchByMaxPrice(number("Maximum price: ")).forEach(System.out::println);break;default:return;}}catch(Exception e){System.out.println("[Error] "+e.getMessage());}}}
 static void addAccommodation(){int t=choice("Type: 1 Apartment, 2 House, 3 Villa: ",1,3);String id=system.generateAccommodationId(),n=text("Name: "),l=text("Location: ");double p=number("Price/night: ");int m=integer("Max guests: ");Accommodation a;if(t==1)a=new Apartment(id,n,l,p,m,true,integer("Bedrooms: "));else if(t==2)a=new House(id,n,l,p,m,true,yes("Garden?"),integer("Floors: "));else a=new Villa(id,n,l,p,m,true,yes("Pool?"),yes("Staff included?"));system.addAccommodation(a);System.out.println("Added "+id);}
 static void updateAccommodation()throws Exception{Accommodation a=system.findAccommodationById(text("Accommodation ID: "));String n=optional("New name: "),l=optional("New location: "),p=optional("New price: ");if(!n.isEmpty())a.setName(n);if(!l.isEmpty())a.setLocation(l);if(!p.isEmpty())a.setPricePerNight(Double.parseDouble(p));a.setAvailable(yes("Available?"));System.out.println(a);}
 static void bookingMenu(){while(true){System.out.println("\n------------- BOOKINGS -------------");System.out.println("1. View all\n2. Create booking\n3. Process next pending\n4. Update status\n5. Cancel\n6. Delete\n0. Back");try{switch(choice(0,6)){case 1:system.getAllBookings().forEach(System.out::println);break;case 2:createBooking();break;case 3:System.out.println(system.processNextPendingRequest());break;case 4:Booking b=system.findBookingById(text("Booking ID: "));System.out.println("1 PENDING 2 CONFIRMED 3 CANCELLED 4 COMPLETED");int s=choice(1,4);system.updateBookingStatus(b.getBookingId(),BookingStatus.values()[s-1]);break;case 5:system.cancelBooking(text("Booking ID: "));break;case 6:system.deleteBooking(text("Booking ID: "));break;default:return;}}catch(Exception e){System.out.println("[Error] "+e.getMessage());}}}
 static void createBooking()throws Exception{String uid=text("User ID: ");String aid=text("Accommodation ID: ");LocalDate in=date("Check-in (yyyy-MM-dd): "),out=date("Check-out (yyyy-MM-dd): ");int g=integer("Guests: ");System.out.println("Created: "+system.createBooking(uid,aid,in,out,g));}
 static void evaluationMenu(){while(true){System.out.println("\n--------- EVALUATION / FEEDBACK ---------");System.out.println("1. View evaluations\n2. Add evaluation\n3. View user rewards/penalties\n0. Back");try{switch(choice(0,3)){case 1:system.getAllEvaluations().forEach(System.out::println);break;case 2:addEvaluation();break;case 3:system.getAllUsers().forEach(u->System.out.println(u.getUserId()+" | "+u.getName()+" | Reward points: "+u.getRewardPoints()+" | Penalties: "+u.getPenaltyCount()));break;default:return;}}catch(Exception e){System.out.println("[Error] "+e.getMessage());}}}
 static void addEvaluation()throws Exception{String b=text("Completed booking ID: ");int r=integer("Rating (1-5): ");String f=text("Feedback: ");System.out.println("Evaluation recorded: "+system.addEvaluation(b,r,f));}
 static int choice(int min,int max){return choice("Enter choice: ",min,max);}static int choice(String prompt,int min,int max){while(true){try{int x=Integer.parseInt(prompt(prompt));if(x>=min&&x<=max)return x;}catch(Exception ignored){}System.out.println("Enter a number from "+min+" to "+max+".");}}
 static String prompt(String p){System.out.print(p);return sc.nextLine().trim();}
 static String text(String p){while(true){String s=prompt(p);if(!s.isEmpty())return s;System.out.println("This field cannot be empty.");}}
 static String optional(String p){return prompt(p);}
 static int integer(String p){while(true){try{return Integer.parseInt(text(p));}catch(Exception e){System.out.println("Enter a whole number.");}}}
 static double number(String p){while(true){try{double x=Double.parseDouble(text(p));if(x>=0)return x;}catch(Exception ignored){}System.out.println("Enter a valid non-negative number.");}}
 static boolean yes(String p){while(true){String s=prompt(p+" (y/n): ");if(s.equalsIgnoreCase("y"))return true;if(s.equalsIgnoreCase("n"))return false;}}
 static LocalDate date(String p){while(true){try{return LocalDate.parse(text(p),F);}catch(Exception e){System.out.println("Use yyyy-MM-dd.");}}}
}
